#!/usr/bin/expect
spawn ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
expect {
    "Overwrite" {send "y\r"; exp_continue}
    "Enter file" {send "\r"; exp_continue}
    "passphrase" {send "\r"; exp_continue}
}

spawn ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key
expect {
    "Overwrite" {send "y\r"; exp_continue}
    "Enter file" {send "\r"; exp_continue}
    "passphrase" {send "\r"; exp_continue}
}

spawn ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key
expect {
    "Overwrite" {send "y\r"; exp_continue}
    "Enter file" {send "\r"; exp_continue}
    "passphrase" {send "\r"; exp_continue}
}